#!/bin/sh

git filter-branch -f --env-filter '
  export GIT_AUTHOR_EMAIL="redacted";
  export GIT_COMMITTER_EMAIL="redacted";
  export GIT_AUTHOR_NAME="redacted";
  export GIT_COMMITTER_NAME="redacted";
  export GIT_AUTHOR_DATE="Thu Jan 1 00:00:00 1970 +0000";
  export GIT_COMMITTER_DATE="Thu Jan 1 00:00:00 1970 +0000";
' \
  --msg-filter "echo 'redacted'" HEAD

